### ISSUE TITLE
Create new 0.2.2 release tag (Python 3 compatibility)

### ISSUE THREAD

**Issue by dgingrich** [trec-kba/many-stop-words#4]
Hi,

I see you just merged in Python 3 support.  Can you add a 0.2.2 release tag  and upload to PyPI?  Right now the only way to install the Python3 support is to explicitly install from the master branch GitHub URL, and even that has a few snags since the version of the master branch is 0.2.1 which collides with the version in PyPI.

Thanks,
Dave

**Comment by BurntSushi** [comment]
cc @johnrfrank What's our procedure for this?

**Comment by johnrfrank** [comment]
@BurntSushi @dgingrich   I ran `git tag -a 0.2.2 -m "python3 support"` and then manually ran  `python setup.py sdist upload` to pypi.  

@BurntSushi :  We could hookup CircleCI to do that second step again; buildbot was doing it previously...
